# Generated by Django 3.2 on 2022-10-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True,primary_key=True, serialize=False, verbose_name='ID')),
                ('release_id', models.IntegerField()),
                ('room_id', models.IntegerField()),
                ('row_id', models.IntegerField()),
                ('column_id', models.IntegerField()),
                ('is_available', models.IntegerField()),
            ],
            options={
                'db_table': 'Seat',
            },
        ),
    ]
