# Generated by Django 3.2 on 2022-10-27 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_id', models.IntegerField()),
                ('content', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('update_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'Announcement',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password_hash', models.CharField(max_length=100)),
                ('password_salt', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('phone', models.IntegerField()),
                ('bank_card', models.IntegerField()),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('update_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('movie_name', models.CharField(max_length=40)),
                ('poster', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('cast', models.CharField(max_length=100)),
                ('introduction', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('update_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'Movie',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('customer_username', models.CharField(max_length=20)),
                ('room_id', models.IntegerField()),
                ('seat_content', models.CharField(max_length=255)),
                ('seat_num', models.IntegerField()),
                ('release_id', models.IntegerField()),
                ('movie_name', models.CharField(max_length=40)),
                ('price', models.FloatField()),
                ('is_cancel', models.IntegerField()),
                ('release_time', models.DateTimeField(default=datetime.datetime.now)),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('update_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_id', models.IntegerField()),
                ('movie_id', models.IntegerField()),
                ('room_id', models.IntegerField()),
                ('price', models.FloatField()),
                ('release_time', models.DateTimeField(default=datetime.datetime.now)),
                ('is_delete', models.IntegerField()),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('update_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'Release',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField()),
                ('row_size', models.IntegerField()),
                ('column_size', models.IntegerField()),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('update_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'Room',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.IntegerField()),
                ('password_hash', models.CharField(max_length=100)),
                ('password_salt', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=20)),
                ('level', models.IntegerField(default=0)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=40)),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('update_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'Staff',
            },
        ),
    ]
